###  CREATE A USER
POST http://localhost:3000/users/91
content-type: application/json

{
    "username": "zaea111ea",
    "password": "testing21561"
}

### GET ALL USERS
GET       http://localhost:3000/users/

### GET A SPECIFIC USER
GET       http://localhost:3000/users/11


###
DELETE  http://localhost:3000/users/81

